### ISSUE TITLE
r/MemesBrasil is a private community

### ISSUE THREAD

**Issue by westhecool** [halitsever/random-memes#27]
## Expected Behavior
gets the meme;

## Actual Behavior
```
    memeObject.data.children[
                    ^

TypeError: Cannot read properties of undefined (reading 'children')
    at Object.fromReddit (C:\Users\xxxxx\node_modules\random-memes\src\lib\fromReddit.js:25:21)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Object.run (C:\xxxxx.js:51:26)
```

## Steps to Reproduce the Problem

  1. `require('random-memes').fromReddit('br')`

## Specifications

  - Version: 3.1.7
  - Platform: win32

**Comment by halitsever** [comment]
First of all, thank you for your feedback!

Do you know of an alternative subreddit for r/memesbrasil?
Is r/DiretoDoZapZap a good alternative?

**Comment by halitsever** [comment]
I changed it to "ItHadToBeBrazil" here is the all predefined subreddits:
https://github.com/halitsever/random-memes/blob/3.2.4/src/constants/subreddits.js

Also i added another parameter to reddit method, its makes possible fetching data from custom subreddit:
https://halitsever.github.io/random-memes/reddit.html
